'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated. 
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Partial Public Class Report_Detail

    '''<summary>
    '''Kode_Emiten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kode_Emiten As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Nama_Emiten control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nama_Emiten As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Kode_Saham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Kode_Saham As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Nama_Saham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Nama_Saham As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Sector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sector As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Sub_Sector control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Sub_Sector As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Jumlah_Saham control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Jumlah_Saham As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scrip_blnc_lokal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scrip_blnc_lokal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scrip_blnc_asing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scrip_blnc_asing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Total_blnc_scrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Total_blnc_scrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scrip_acct_lokal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scrip_acct_lokal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scrip_acct_asing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scrip_acct_asing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Total_acct_scrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Total_acct_scrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scripless_blnc_lokal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scripless_blnc_lokal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scripless_blnc_asing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scripless_blnc_asing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Total_blnc_scripless control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Total_blnc_scripless As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scripless_acct_lokal control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scripless_acct_lokal As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Scripless_acct_asing control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Scripless_acct_asing As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Total_acct_scripless control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Total_acct_scripless As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Perbandingan_Scrip control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Perbandingan_Scrip As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Perbandingan_Scripless control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Perbandingan_Scripless As Global.System.Web.UI.WebControls.Label

    '''<summary>
    '''Selisih control.
    '''</summary>
    '''<remarks>
    '''Auto-generated field.
    '''To modify move field declaration from designer file to code-behind file.
    '''</remarks>
    Protected WithEvents Selisih As Global.System.Web.UI.WebControls.Label
End Class
